language: python
python: 3.6.8
script: python main.py
deploy:
  provider: heroku
  api_key:
    secure: WNbVgzbowwzEBpddrOPOoNRKFrPwx+2RTQbsJZWCHtrj5rgkGdPOR0OyinZu2T7snpJkHM/n3W/FSyWKlEJmrEYw7WCpBDrCDtAW9cm+qAHN27fTuGkn7F3S1UEcrhzkqPTK8oLXp22jintsO2/hc9LjWipHPf7L+w9n963czXyH6ZD/Bev8Pozh/cMWOVYsEg23HEk3Z61YF3kwRvRUK+Lvmm1Dl52CBQWew/BFuDhXC5Zvw6kOY53twSD/twc9k1sksknlZmzW0Tb6xqEbS4Y9ppJdomdW18z7B71gbmkl6WPzEqdjFsurmjxIol+/nKJbkBdoyCZCq0KZuZ5V/f32xIAcvsPRxLBl197EifnaXNCMMbOQz/k3oeldq9005LqlmydRVRlyOfm61EwO7tJkrkVj86uVSq2GEPcOP2SyakHpQM9vPag8NCfh5x7aWCWfZ5u3cGik9Q4vYeHeruN2/jshhY4gdV265FAMoKPs9gJzMGlLKspbnaLK5HP5vgD8ss8cDrHU7FhT18Lz/Ee1BiwQkV4txAQ/3J8OLzqqA6zFICf1Gw9450Mk7xPfhWKmC+tNKZwSL+kKozSfNyqSuoBz3TOElnOoUTBD/ndm98J/7Tr9C2yY/wcPVy78O1jqJH4TDpPm4zDRQYJnrT3nerP5mUfqaTUWARyYtto=
  app: gamerbodbot
  on:
    repo: mjpin7/GamerBodBot
env:
  token:
    secure: v7tEgYOGcQxsF4YotfRO26miKWLid3fUz/gxYyrnI13Ah0hQX++oQ//7Q3yB1HkjmAa5jzrs+jny0Ik3H0Xb4HEImf7ID7M+Q8dfeEvrKITmp22r5cAfhXuzWbhZsCSfFMubDrdt9A5VvKolJpCPcN3wW1EuEK7UbPDBSMZWhbcUNzdYLmWJCMvcJ7GarVZeCSSzYHQTomozNuUHleXzDe/5htbkVogyP8ReZr3unEnQ49vtqnXw4EEgsXSGUWhrLf48+qeUjwIEJLXrY40KZ0Ogl97u68FJS5gZ21NyMMGJR5nFptdCtX1+yYMbJHdg+/DOB3ZqC8VrYtBWH47Jul+e2N1bePwyifNamF6x1UpA8rppQV3sFtnRSOcvv+ghvE4fAFBLnulnUXIeyAaC5pYmIthn55h3JFD5zvP+yzfaokkTxFRlz0g2pTup0MdzkBVVo5ZKPdFuN+1kPnobJdt34INZ7ExNiAlRKOr7dXS0RhyzVCCR1dZlYn7N3QprT7QcEVTs0PUGdLH+pIdCmL46p+A4uazVhh45Yy9yQMTQW1g0a1evSI3PEPWk4QEi3x4yD3GzDgbWqWVfFH+0Qsf+8SlY/OH2JVrxIpNP6Jb6c+87XObYvGqfUeul/sTKGX88xUjJZBKyMw85EcdtFTxYgv7otmJ8x09IlN0QRpM=
